/**
 * 自动生成组件库入口文件
 * 扫描 src/components 目录，生成 src/index.ts
 */

const fs = require('fs');
const path = require('path');

const COMPONENTS_DIR = path.resolve(__dirname, '../src/components');
const OUTPUT_FILE = path.resolve(__dirname, '../src/index.ts');

/**
 * 获取所有组件目录名
 */
function getComponentNames() {
  const entries = fs.readdirSync(COMPONENTS_DIR, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

/**
 * 生成入口文件内容
 */
function generateEntryContent(componentNames) {
  const imports = componentNames
    .map((name) => `import ${name} from './components/${name}';`)
    .join('\n');

  const componentsList = componentNames.join(', ');
  const exports = componentNames.join(', ');

  return `// Auto-generated by scripts/generate-entry.js
// 全局样式
import './styles/index.less';

// 组件导入
${imports}

// 组件列表
const components = [${componentsList}];

// Vue.use() 全量安装
function install(Vue: any): void {
  components.forEach((component) => {
    Vue.use(component);
  });
}

// 导出组件
export { ${exports} };

// 导出默认安装方法
export default {
  install,
};
`;
}

/**
 * 主函数
 */
function main() {
  console.log('🔍 扫描组件目录...');
  const componentNames = getComponentNames();

  if (componentNames.length === 0) {
    console.log('⚠️  未找到任何组件');
    return;
  }

  console.log(`📦 找到 ${componentNames.length} 个组件:`);
  componentNames.forEach((name) => console.log(`   - ${name}`));

  const content = generateEntryContent(componentNames);
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');

  console.log(`✅ 入口文件已生成: ${OUTPUT_FILE}`);
}

main();

