// Auto-generated by scripts/generate-entry.js
// 全局样式
import './styles/index.less';

// 组件导入
import Button from './components/Button';
import SearchInput from './components/SearchInput';

// 组件列表
const components = [Button, SearchInput];

// Vue.use() 全量安装
function install(Vue: any): void {
  components.forEach((component) => {
    Vue.use(component);
  });
}

// 导出组件
export { Button, SearchInput };

// 导出默认安装方法
export default {
  install,
};
